wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684156065.254903
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 14
      - 23
      4: 3.10.8
      5: 0.15.0
      8:
      - 1
      - 5
