wandb_version: 1

learning_rate:
  desc: null
  value: 0.0055
learning_rate_decay:
  desc: null
  value: 0.16
momentum:
  desc: null
  value: 0.9
epsilon:
  desc: null
  value: 1
RMS_decay/alpha:
  desc: null
  value: 0.9
weight_decay/L2:
  desc: null
  value: 4.0e-05
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 25
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691438793.174612
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.15.7
      8:
      - 5
