wandb_version: 1

model:
  desc: null
  value: inception
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.9
epsilon:
  desc: null
  value: 1.0
epochs:
  desc: null
  value: 15
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683186881.769251
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.15.0
      8:
      - 1
      - 5
