wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
learning_rate_decay:
  desc: null
  value: 0.85
weight_decay:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 25
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684920899.367841
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.15.0
      8:
      - 5
