wandb_version: 1

learning_rate:
  desc: null
  value: 0.0055
learning_rate_decay:
  desc: null
  value: 0.9
momentum:
  desc: null
  value: 0.9
epsilon:
  desc: null
  value: 1
RMS_decay/alpha:
  desc: null
  value: 0.9
weight_decay/L2:
  desc: null
  value: 4.0e-05
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697562588.066642
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
