wandb_version: 1

RMS_weight_decay:
  desc: null
  value: 0.9
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1685972983.582501
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.13
      5: 0.13.4
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 20
epsilon:
  desc: null
  value: 1.0
learning_rate:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.9
