wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-06
weight_decay:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 25
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689713836.239885
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.15.5
      8:
      - 5
