wandb_version: 1

batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 1.0e-07
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683299001.688389
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.15.0
      8:
      - 1
      - 5
